Commit HTML, CSS, JS, and image files
I spent over an hour trying to push this locally but I kept getting an error:
To https://github.com/JenniferToops/100devs-slot-machine.git
 ! [rejected]        answer -> answer (non-fast-forward)
error: failed to push some refs to 'https://github.com/JenniferToops/100devs-slot-machine.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.